### ISSUE TITLE
Browsers doesn't persist in file systems after running buildpack

### ISSUE THREAD

**Issue by Thomas-Boi** [binoche9/playwright-python-heroku-buildpack#1]
Hello,

For some reason, the browsers installed by the buildpacks aren't found after Heroku is deployed.

Installation works great. I set `PLAYWRIGHT_BROWSERS_PATH=./browsers`:

![image](https://github.com/binoche9/playwright-python-heroku-buildpack/assets/43018778/2526f5f2-b8a4-4821-aa2c-8217758047e1)

However, afterwards, Playwright still doesn't run. I SSH into the instance and I couldn't find the `browsers` folder anywhere in `~` or `/`.

Would appreciate your help on this because I feel like I'm so close 😄

**Comment by binoche9** [comment]
Oof I should probably archive this project because I wasn't quite able to figure this out either 😞 I've resorted to having an `playwright install chromium` in my Procfile on startup which is good enough for the small project I used it for

**Comment by Thomas-Boi** [comment]
Thanks for getting back to me. I'll keep looking then. I might fork your project and work on it if I ever found the solution.

**Comment by Thomas-Boi** [comment]
> Oof I should probably archive this project because I wasn't quite able to figure this out either 😞 I've resorted to having an `playwright install chromium` in my Procfile on startup which is good enough for the small project I used it for

I think I've found the reason:

According to [this Heroku link], the parameters passed to `compile` are:
```
bin/compile BUILD_DIR CACHE_DIR ENV_DIR
```

Your `compile` code relies on `ENV_DIR` 

```
# $3 is the environment dir
env_dir="$3"

# Check the environment dir for the `PLAYWWRIGHT_BROWSERS_PATH`
# variable and if it exists export it
if [ -d "$env_dir" ]; then
    for e in $(ls $env_dir); do
        if [ "$e" == "PLAYWRIGHT_BROWSERS_PATH" ]; then
            export "$e=$(cat $env_dir/$e)"
        fi
    done
fi
```

However, according to the Heroku link, the `ENV_DIR` is merely where the env variable config files are stored. It's the `BUILD_DIR` that will be used to package the slug.  Thus, if we modify the path to this directory, we might be able to fix it.

I'll make my own repo to see if this works. If it does, I'll let you know.

**Comment by binoche9** [comment]
Let me know if you figure out what I couldn't - I'd love to use it too 😄

**Comment by Thomas-Boi** [comment]
> Let me know if you figure out what I couldn't - I'd love to use it too 😄

Got a working solution for me [here](https://github.com/Thomas-Boi/heroku-python-playwright-chromium/tree/v0.1.0). I only use Chromium though and haven't tested Firefox or Webkit BUT it should work
